# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BiosKimGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import uic
import analysis1
import sys
import resources_rc
import webbrowser
import urllib.parse

class fvmutaciones(QtWidgets.QDialog):
    def __init__(self, frag, peptide, New_frag, New_Peptide):
        super(fvmutaciones, self).__init__()
        uic.loadUi('mutationFinal.ui', self)

        self.frag = frag
        self.peptide = peptide
        self.New_frag = New_frag
        self.New_Peptide = New_Peptide
        try:
            #print(f"se recibió {New_frag}")
            #print(f"Los tipos de datos son: {type(frag)}, {type(peptide)}, {type(New_frag)}, {type(New_Peptide)}")
            #Data Pass
            if hasattr(self, 'old_DNA'):
                self.old_DNA.setPlainText(frag)
            if hasattr(self, 'old_AA'):
                self.old_AA.setPlainText(peptide)
            if hasattr(self, 'mutated_AA'):
                self.mutated_AA.setPlainText(New_Peptide)
            if hasattr(self, 'mutated_DNA'):
                self.mutated_DNA.setPlainText(New_frag)

            if hasattr(self, 'compareBttn'):
                self.compareBttn.clicked.connect(self.compareProtein)
        except AttributeError as e:
            print(f"Uno de los widgets no existe: {e} ")

    def compareProtein(self):

        fastaTypo = (
            f">Proteína_No_Modificada\n{self.peptide}\n"
            f">Proteína_Mutada\n{self.New_Peptide}"
        )
        cb = QtWidgets.QApplication.clipboard()
        cb.setText(fastaTypo, mode=cb.Clipboard)

        webbrowser.open("https://www.ncbi.nlm.nih.gov/tools/cobalt/cobalt.cgi")
        self.advise.setText("Sequences Coppied to clipboard!")

class vmutaciones(QtWidgets.QDialog):
    def __init__(self, frag, peptide):
        super(vmutaciones, self).__init__()
        uic.loadUi('mutationIntermidiate.ui', self)
        #Functions:
        if hasattr(self, 'DNAStrand'):
            self.DNAStrand.setText(frag)
        if hasattr(self, 'nextBttn'):
            self.nextBttn.clicked.connect(self.openNext)

        #modifVARs:
        self.peptide = peptide
        self.fragment = frag
    def openNext(self):
        modDna = self.DNAStrand.toPlainText().strip().upper() #create e new name var for this shit

        print(f'ADN modificado a {modDna}')
        result = analysis1.Transcripcion(modDna) #the new var is used isntead of self.DNAStrand
        if hasattr(self, 'fragment') and modDna and result:
            self.ventanaFinal = fvmutaciones(self.fragment, self.peptide, modDna, result)
            self.ventanaFinal.show()
            self.close()
        else:
            self.ventanaFinal = fvmutaciones("Error", "Error", "ADN Vacio","No hay proteína")
            self.ventanaFinal.show()


class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        uic.loadUi('BiosKimGUI.ui', self)
        #Para el path del archivo:
        self.ruta = None
        #Conecciones con los botones y demás.
        self.BrowseBttn.clicked.connect(self.open_file_dialog)
        self.actionGenerar_Mutaciones.triggered.connect(self.abrirMutaciones)
        self.GCBttn.clicked.connect(self.PrimerAnalisis)
        self.AnalysisBttn.clicked.connect(self.ejecutar_analysis)
        self.BlastBttn.clicked.connect(self.BlastX)

    def BlastX(self):
        if hasattr(self, 'proteina') and self.proteina:
            secuencia = self.proteina
            url = (
                f"https://blast.ncbi.nlm.nih.gov/Blast.cgi?"
                f"PROGRAM=blastp&"
                f"PAGE_TYPE=BlastSearch&"
                f"LINK_LOC=blasthome&"
                f"QUERY={secuencia}"
            )
            print(url)
            webbrowser.open(url)
        else:
            if hasattr(self, 'AnalysisResult'):
                self.AnalysisResult.setText("Error: Primero Debe Realizar un Analysis")
    def ejecutar_analysis(self):
        try:
            file = self.ruta
            rango = self.limits.text()
            if not file or not rango:
                if hasattr(self, 'AnalysisResult'):
                    self.AnalysisResult.setText("Falta seleccionar archivo o ingresar rango")
                return

            result = analysis1.analysis(self.ruta, self.limits.text())
            if isinstance(result, tuple):
                resultmArn = "".join(result[1])
                result35 = "".join(result[2])
                protSeq = result[3]
                estats = result[4]
                self.fragmento = result[5]
                self.proteina = result[3] #Sends it to def_BlastX to operate

                texto_a = ""
                for aa, datos in estats.items():
                    texto_a += f"{aa}: {datos['cantidad']} ({datos['porcentaje']}%)\n"
                #Recuerda que tu secuencia de proteínas en formato normal es protSeq
                finalMSG = (
                f"{result[0]}\n\n"
                f"cadena complementaria (3'-5'):\n{result35}\n\n"
                f"mARN complementario: \n{resultmArn}\n\n"
                f"La secuencia proteíca es: \n{protSeq}\n\n"
                f"Estadisticas:\n{texto_a}"
                )
                if hasattr(self, 'AnalysisResult'):
                    self.AnalysisResult.setText(finalMSG)
                else:
                    print("Error: No se encuentra el widget")
            else:
                if hasattr(self, 'AnalysisResult'):
                    self.AnalysisResult.setText(str(result))
        except Exception as e:
            print(f"Crash Evitado. Error: {e}")
    def PrimerAnalisis(self):
        if self.ruta:
            resultado = analysis1.readFile(self.ruta)
            if isinstance(resultado, tuple):
                percentage = resultado[0]
                totalNucleotide = resultado[1]

                self.resultGC.setText(f"GC% es: {percentage}%")
                if hasattr(self, 'linneEdit'):
                    self.linneEdit.setText(f"Hay {totalNucleotide} Nucletidos")
                if hasattr(self, 'nucleotide'):
                    self.nucleotide.setText(f"{totalNucleotide}")
            else:
                self.resultGC.setText(resultado)
        else:
            self.resultGC.setText("Error: Porfavor seleccione archivo")

    def abrirMutaciones(self):
        #se verifica si hay un elemento para tomar (es decír poder obtener el fragmento)
        if hasattr(self, 'fragmento') and self.fragmento:
            #y se pasa la varaible a la ventana.
            self.ventanaMutaciones = vmutaciones(self.fragmento, self.proteina)

        else:
            self.ventanaMutaciones = vmutaciones("No se ha seleccionado ninguna secuencia o no se ha hecho un analisis previo")
        self.ventanaMutaciones.show()
    def open_file_dialog(self):
        options = QtWidgets.QFileDialog.Options()
        file_path, _ = QtWidgets.QFileDialog.getOpenFileName(self, "Select File", "", "All files (*);; Python Files (*.py)", options=options)

        if file_path:
            #To make The var Accesible for other scripts
            self.ruta = file_path
            self.fileRef.setText(file_path) #In here is where the path is seen in the text (screen).
            print(f"Selected file: {file_path}")
            #Btw i already verified the type its a STR.

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    #MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.show()
    #ui.setupUi(MainWindow)
    #MainWindow.show()
    sys.exit(app.exec_())

#El siguiente dato no lo borres sino no funciona nada:
#
