# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mutationFinal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mutaciones_2(object):
    def setupUi(self, mutaciones_2):
        mutaciones_2.setObjectName("mutaciones_2")
        mutaciones_2.resize(505, 396)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mutaciones_2.setWindowIcon(icon)
        self.textEdit = QtWidgets.QTextEdit(mutaciones_2)
        self.textEdit.setGeometry(QtCore.QRect(270, 60, 221, 151))
        self.textEdit.setObjectName("textEdit")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(mutaciones_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 60, 221, 151))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(mutaciones_2)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 250, 221, 131))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(mutaciones_2)
        self.textEdit_3.setGeometry(QtCore.QRect(270, 250, 221, 131))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label = QtWidgets.QLabel(mutaciones_2)
        self.label.setGeometry(QtCore.QRect(20, 40, 111, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(mutaciones_2)
        self.label_2.setGeometry(QtCore.QRect(270, 40, 141, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(mutaciones_2)
        self.label_3.setGeometry(QtCore.QRect(20, 230, 151, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(mutaciones_2)
        self.label_4.setGeometry(QtCore.QRect(270, 230, 131, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(mutaciones_2)
        self.label_5.setGeometry(QtCore.QRect(220, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(mutaciones_2)
        QtCore.QMetaObject.connectSlotsByName(mutaciones_2)

    def retranslateUi(self, mutaciones_2):
        _translate = QtCore.QCoreApplication.translate
        mutaciones_2.setWindowTitle(_translate("mutaciones_2", "Dialog"))
        self.label.setText(_translate("mutaciones_2", "Old Dna Strand:"))
        self.label_2.setText(_translate("mutaciones_2", "Mutated Dna Strand:"))
        self.label_3.setText(_translate("mutaciones_2", "New Amino Acid Chain:"))
        self.label_4.setText(_translate("mutaciones_2", "Mutated Dna Strand:"))
        self.label_5.setText(_translate("mutaciones_2", "Results:"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mutaciones_2 = QtWidgets.QDialog()
    ui = Ui_mutaciones_2()
    ui.setupUi(mutaciones_2)
    mutaciones_2.show()
    sys.exit(app.exec_())
