# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mutationIntermidiate.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import uic

class Ui_mutaciones_1(object):

    def setupUi(self, mutaciones_1):
        mutaciones_1.setObjectName("mutaciones_1")
        mutaciones_1.resize(260, 321)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mutaciones_1.setWindowIcon(icon)
        self.Title = QtWidgets.QLabel(mutaciones_1)
        self.Title.setGeometry(QtCore.QRect(90, 10, 71, 16))
        self.Title.setObjectName("Title")
        self.DNAStrand = QtWidgets.QTextEdit(mutaciones_1)
        self.DNAStrand.setGeometry(QtCore.QRect(10, 30, 241, 161))
        self.DNAStrand.setObjectName("DNAStrand")
        self.info1 = QtWidgets.QLabel(mutaciones_1)
        self.info1.setGeometry(QtCore.QRect(20, 190, 231, 21))
        self.info1.setObjectName("info1")
        self.info2 = QtWidgets.QLabel(mutaciones_1)
        self.info2.setGeometry(QtCore.QRect(30, 210, 221, 20))
        self.info2.setObjectName("info2")
        self.nextBttn = QtWidgets.QPushButton(mutaciones_1)
        self.nextBttn.setGeometry(QtCore.QRect(80, 270, 93, 28))
        self.nextBttn.setObjectName("nextBttn")

        self.retranslateUi(mutaciones_1)
        QtCore.QMetaObject.connectSlotsByName(mutaciones_1)

    def retranslateUi(self, mutaciones_1):
        _translate = QtCore.QCoreApplication.translate
        mutaciones_1.setWindowTitle(_translate("mutaciones_1", "Dialog"))
        self.Title.setText(_translate("mutaciones_1", "DNA Strand"))
        self.info1.setText(_translate("mutaciones_1", "You can either remove, add or exchange"))
        self.info2.setText(_translate("mutaciones_1", "Nucleotides above. Then click next"))
        self.nextBttn.setText(_translate("mutaciones_1", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    ui = Ui_mutaciones_1()
    ui.show()
    sys.exit(app.exec_())
