# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mutaciones.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mutaciones(object):
    def setupUi(self, Mutaciones):
        Mutaciones.setObjectName("Mutaciones")
        Mutaciones.resize(398, 574)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Mutaciones.setWindowIcon(icon)
        self.buttonBox = QtWidgets.QDialogButtonBox(Mutaciones)
        self.buttonBox.setGeometry(QtCore.QRect(50, 540, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.DnaStrand = QtWidgets.QTextEdit(Mutaciones)
        self.DnaStrand.setGeometry(QtCore.QRect(20, 40, 351, 191))
        self.DnaStrand.setObjectName("DnaStrand")
        self.getDnaBttn = QtWidgets.QPushButton(Mutaciones)
        self.getDnaBttn.setGeometry(QtCore.QRect(20, 10, 93, 28))
        self.getDnaBttn.setObjectName("getDnaBttn")
        self.mutacionesBttn = QtWidgets.QPushButton(Mutaciones)
        self.mutacionesBttn.setGeometry(QtCore.QRect(20, 240, 351, 28))
        self.mutacionesBttn.setObjectName("mutacionesBttn")
        self.mutatedAAchain = QtWidgets.QTextEdit(Mutaciones)
        self.mutatedAAchain.setGeometry(QtCore.QRect(20, 280, 351, 191))
        self.mutatedAAchain.setObjectName("mutatedAAchain")

        self.retranslateUi(Mutaciones)
        self.buttonBox.accepted.connect(Mutaciones.accept) # type: ignore
        self.buttonBox.rejected.connect(Mutaciones.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Mutaciones)

    def retranslateUi(self, Mutaciones):
        _translate = QtCore.QCoreApplication.translate
        Mutaciones.setWindowTitle(_translate("Mutaciones", "Dialog"))
        self.getDnaBttn.setText(_translate("Mutaciones", "Get DNA"))
        self.mutacionesBttn.setText(_translate("Mutaciones", "Generar Mutaciones"))
        self.mutatedAAchain.setHtml(_translate("Mutaciones", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mutaciones = QtWidgets.QDialog()
    ui = Ui_Mutaciones()
    ui.setupUi(Mutaciones)
    Mutaciones.show()
    sys.exit(app.exec_())
