# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import uic
import sys

class Ui_Biokim(QtWidgets.QMainWindow):
    def __init__(self):
        super(Ui_Biokim, self).__init__()

        uic.loadUi('test1.ui', self)
        self.ruta = None
        self.BrowseBttn.clicked.connect(self.open_file_dialog)

    def open_file_dialog(self):
        options = QtWidgets.QFileDialog.Options()
        file_path, _ = QtWidgets.QFileDialog.getOpenFileName(self, "Select File", "", "All Files (*);;Python Files (*.py)", options=options)

        if file_path:
            # to make the vatriable accesible for other scripts:
            self.ruta = file_path
            self.fileRef.setText(file_path)
            print(f"Selected file: {file_path}")
            # verified the file_path is a str type.


    def setupUi(self, Biokim):
        Biokim.setObjectName("Biokim")
        Biokim.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Biokim)
        self.centralwidget.setObjectName("centralwidget")
        self.BrowseBttn = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseBttn.setGeometry(QtCore.QRect(300, 40, 93, 31))
        self.BrowseBttn.setObjectName("BrowseBttn")
        self.fileRef = QtWidgets.QLineEdit(self.centralwidget)
        self.fileRef.setGeometry(QtCore.QRect(50, 40, 241, 31))
        self.fileRef.setObjectName("fileRef")
        self.GCBttn = QtWidgets.QPushButton(self.centralwidget)
        self.GCBttn.setGeometry(QtCore.QRect(50, 90, 111, 28))
        self.GCBttn.setObjectName("GCBttn")
        self.GCResult = QtWidgets.QLineEdit(self.centralwidget)
        self.GCResult.setGeometry(QtCore.QRect(180, 90, 113, 22))
        self.GCResult.setObjectName("GCResult")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(520, 40, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(480, 70, 171, 131))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.DNA_RNABttn = QtWidgets.QPushButton(self.centralwidget)
        self.DNA_RNABttn.setGeometry(QtCore.QRect(50, 160, 181, 31))
        self.DNA_RNABttn.setObjectName("DNA_RNABttn")
        self.RNAResult = QtWidgets.QLineEdit(self.centralwidget)
        self.RNAResult.setGeometry(QtCore.QRect(250, 170, 113, 22))
        self.RNAResult.setObjectName("RNAResult")
        Biokim.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Biokim)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile_info = QtWidgets.QMenu(self.menubar)
        self.menuFile_info.setObjectName("menuFile_info")
        Biokim.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Biokim)
        self.statusbar.setObjectName("statusbar")
        Biokim.setStatusBar(self.statusbar)
        self.actionSelect_File = QtWidgets.QAction(Biokim)
        self.actionSelect_File.setObjectName("actionSelect_File")
        self.menuFile_info.addAction(self.actionSelect_File)
        self.menubar.addAction(self.menuFile_info.menuAction())

        self.retranslateUi(Biokim)
        QtCore.QMetaObject.connectSlotsByName(Biokim)

    def retranslateUi(self, Biokim):
        _translate = QtCore.QCoreApplication.translate
        Biokim.setWindowTitle(_translate("Biokim", "MainWindow"))
        self.BrowseBttn.setText(_translate("Biokim", "Browse"))
        self.GCBttn.setText(_translate("Biokim", "Calculate GC %"))
        self.pushButton.setText(_translate("Biokim", "Extract data"))
        self.DNA_RNABttn.setText(_translate("Biokim", "Show DNA and RNA Strands"))
        self.menuFile_info.setTitle(_translate("Biokim", "Menu"))
        self.actionSelect_File.setText(_translate("Biokim", "Select File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    #Biokim = QtWidgets.QMainWindow()
    ui = Ui_Biokim()
    ui.show()
    #ui.setupUi(Biokim)
    #Biokim.show()
    sys.exit(app.exec_())
